spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nullnull
    driverClassName: com.mysql.cj.jdbc.Driver
    root: {$root}
    password: {$password}
    
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

jwt:
  secret:
    key:
      1a1b9536d65432b16d4ded7f2814c8e5105ceae7ced4e173b086c564f2efa609d03c8ab84a78492f3175c0ce8ef792d6e55157f34777628f6f55163ef115bfe4

ADMIN_TOKEN = 11

profile:
  image:
    directory: "your/profile/image/directory"

logging:
  level:
    root: info
    com:
      example: debug
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
        
