spring:
  profiles:
    default: local
  datasource:
    url: ${DB_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

jwt:
  secret:
    key:
      ${JWT_KEY}

admin:
  token:
    ${ADMIN_TOKEN}

#profile:
#  image:
#    directory: "your/profile/image/directory"

logging:
  level:
    root: info
    com:
      example: debug
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
